name: Publish NPM package

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [published]

jobs:
  publish:
    name: Push NPM package to npmjs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Publish
        if: '!github.event.release.prerelease'
        run: npm publish --access public

      - name: Publish PRERELEASE
        if: 'github.event.release.prerelease'
        run: npm publish --access public --tag next
